# SonarCloud/SonarQube project configuration
sonar.projectKey=Lab7

sonar.organization=PK_Materials_AM
sonar.projectName=Budget App

# Path to the source directories
sonar.sources=BudgetApp

# Exclusions to optimize scan size and focus on source code
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.mvn/**,**/mvnw*,**/*.spec.ts,**/*.test.ts,**/.DS_Store,**/.vscode/**

# Source encoding
sonar.sourceEncoding=UTF-8

# Java Specific Configurations (needed for Java analysis)
sonar.java.binaries=BudgetApp/backend/target/classes
