spring.application.name=PASiR_Parkovskyi_Nikita
spring.config.import=optional:file:.env[.properties]

# Server Port
server.port=${SERVER_PORT:8081}

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE:nazwisko_imie_grupa_spring}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER:user-ni}
spring.datasource.password=${MYSQL_PASSWORD:strongUserPass123!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# GraphQL
spring.graphql.http.path=/graphql
spring.graphql.schema.file-extensions=.graphql,.graphqls,.gqls

# JWT
app.jwt.secret=${JWT_SECRET:superSecretKeyForJwtTokensUsedOnlyInProductionConsolidatedMonoRepositoryBudgetApp!}

# CORS Configuration
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:*,http://127.0.0.1:*}
